model: gpt-4o
prompt_data_path: /home/jayanta/Documents/Bangla_R&N_Bias_Detection/Data/RefinedEBEData/ebe_religion_prompts.csv
storage_path: /home/jayanta/Documents/Bangla_R&N_Bias_Detection/Data/EBE_response/ebe_religion_response.csv
template_version: ebe
response_processor_version: ebe